INTERACTIVE_MODELS_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/GrabCut"
BERKELEY_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/Berkeley"
DAVIS_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/DAVIS"
DUTS_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/DUTS"
COCO_MVAL_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/COCO_MVal"
TETRIS_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/TETRIS"
INTERACTIONSET_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/FOR_TEST"
USER_STUDY_NEW_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/FOR_TEST"
HELA_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/HeLa"
WBC_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/WBC/wbc"
ACDC_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/ScribbleVC/ACDC"
BUID_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/BUID/npy_resized1024"

SBD_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/SBD"
COCO_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/coco2017"
LVIS_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/LVIS"
MEDSCRIBBLE_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/MedScribble"
DUTS_SCRIBBLE_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/DUTS"
DAVIS_SCRIBBLE_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/DAVIS"
USERSTUDY_SCRIBBLE_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/User_study"
GRABCUT_SCRIBBLE_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/GrabCut"
OPENIMAGES_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/OpenImages"
ADE20K_PATH: "/home/jovyan/shares/SR006.nfs2/pishugin/rclicks/datasets/ADE20K/ade20k/samples_1000/"
