INTERACTIVE_MODELS_PATH: ""
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "../datasets/GrabCut"
BERKELEY_PATH: "../datasets/Berkeley"
DAVIS_PATH: "../datasets/DAVIS"
DUTS_PATH: "../datasets/DUTS"
COCO_MVAL_PATH: "../datasets/COCO_MVal"
TETRIS_PATH: "../datasets/TETRIS"
INTERACTIONSET_PATH: "../datasets/FOR_TEST"
USER_STUDY_NEW_PATH: "../datasets/FOR_TEST"
HELA_PATH: "../datasets/HeLa"
WBC_PATH: "../datasets/WBC/wbc"
ACDC_PATH: "../datasets/ScribbleVC/ACDC"
BUID_PATH: "../datasets/BUID/npy_resized1024"

SBD_PATH: "../datasets/SBD"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
MEDSCRIBBLE_PATH: "../datasets/MedScribble"
DUTS_SCRIBBLE_PATH: "../datasets/DUTS"
DAVIS_SCRIBBLE_PATH: "../datasets/DAVIS"
USERSTUDY_SCRIBBLE_PATH: "../datasets/User_study"
GRABCUT_SCRIBBLE_PATH: "../datasets/GrabCut"
OPENIMAGES_PATH: "./datasets/OpenImages"
ADE20K_PATH: "../datasets/ADE20K/ade20k/samples_1000/"
